apiVersion: batch/v1
kind: CronJob
metadata:
  name: sample-cron-job
spec:
  schedule: "*/1 * * * *" #	Run every minute
  jobTemplate:
    spec:
      completions: 3
      parallelism: 3
      template:
        spec:
          containers:
            - name: sample-cron-job
              image: busybox:latest
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - date; echo Hello!
          restartPolicy: OnFailure
